<a href="https://colab.research.google.com/github/BRakesha/ipl-data-analysis-python/blob/main/ipl_EDA_CLEAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import kagglehub
path = kagglehub.dataset_download("patrickb1912/ipl-complete-dataset-20082020")

Using Colab cache for faster access to the 'ipl-complete-dataset-20082020' dataset.

In [ ]:
path

'/kaggle/input/ipl-complete-dataset-20082020'

In [ ]:
ipl=pd.read_csv('/kaggle/input/ipl-complete-dataset-20082020/matches.csv')

In [ ]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

## WE are changing values in season columns values

In [ ]:
ipl['season'].unique()

array(['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022',
       '2023', '2024'], dtype=object)

In [ ]:
ipl['season'].replace({'2007/08':2008,
                       '2009/10':2010,
                       '2020/21':2020},inplace=True)

/tmp/ipykernel_3311/3495467152.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ipl['season'].replace({'2007/08':2008,

## filling null values in city columns as a UnKnown

In [ ]:
ipl['city']=ipl['city'].fillna('Unknown')

## we are filling normal in method column because in cricket there is 2 chance

1.Normal Method
2.DLS Method(By reducing Over)

In [ ]:
ipl['method'].unique()

array([nan, 'D/L'], dtype=object)

In [ ]:
ipl['method']=ipl['method'].fillna('Normal')

In [ ]:
ipl['city'].nunique()

37

## we are mantaining cities name same
because some of the cities having different names

In [ ]:
ipl['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', 'Unknown', 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah', 'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'],
      dtype=object)

In [ ]:
ipl['city']=ipl['city'].replace({'Bangalore':'Bengaluru',
                     'Navi Mumbai':'Mumbai'})

## we are changing team name some team changes there names like 1.rcb 2.pbks 3.delhi etc

In [ ]:
pd.concat([ipl['team1'],ipl['team2']]).unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [ ]:
ipl['team1']=ipl['team1'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
                     'Kings XI Punjab':'Punjab Kings',
                     'Delhi Daredevils':'Delhi Capitals',
                     'Deccan Chargers':'Sunrisers Hyderabad',
                     'Pune Warriors':'Rising Pune Supergiants',
                     'Rising Pune Supergiants':'Rising Pune Supergiant'})

In [ ]:
ipl['team2']=ipl['team2'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
                     'Kings XI Punjab':'Punjab Kings',
                     'Delhi Daredevils':'Delhi Capitals',
                     'Deccan Chargers':'Sunrisers Hyderabad',
                     'Pune Warriors':'Rising Pune Supergiants',
                     'Rising Pune Supergiants':'Rising Pune Supergiant'})

## we are changing date column exact date datype because previous it is object datatype

In [ ]:
ipl['date']=pd.to_datetime(ipl['date'])

In [ ]:
ipl['season']=ipl['season'].astype(int)

## changing Values In Winner Coulums As same team Some Team changes There name

In [ ]:
ipl['winner']=ipl['winner'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
                     'Kings XI Punjab':'Punjab Kings',
                     'Delhi Daredevils':'Delhi Capitals',
                     'Deccan Chargers':'Sunrisers Hyderabad',
                     'Pune Warriors':'Rising Pune Supergiants',
                     'Rising Pune Supergiants':'Rising Pune Supergiant'})



ipl['toss_winner']=ipl['toss_winner'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
                     'Kings XI Punjab':'Punjab Kings',
                     'Delhi Daredevils':'Delhi Capitals',
                     'Deccan Chargers':'Sunrisers Hyderabad',
                     'Pune Warriors':'Rising Pune Supergiants',
                     'Rising Pune Supergiants':'Rising Pune Supergiant'})

In [ ]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   int64
 2   city             1095 non-null   object
 3   date             1095 non-null   datetime64[ns]
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           1095 non-null   object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(2), object(14)
memory usage: 171.2+ KB

### we are Filling player of match is No award when match was suspended

In [ ]:
ipl['player_of_match'].fillna('No Award',inplace=True)

/tmp/ipykernel_3311/669362055.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ipl['player_of_match'].fillna('No Award',inplace=True)

### we are filling winner is no result when match was suspended

In [ ]:
ipl['winner'].fillna("No Result",inplace=True)

/tmp/ipykernel_3311/731123194.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ipl['winner'].fillna("No Result",inplace=True)

## we are replacing super_over values with True or False for future operations

In [ ]:
ipl['super_over']=ipl['super_over'].replace({'N':False,'Y':True})

/tmp/ipykernel_3311/3939676690.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ipl['super_over']=ipl['super_over'].replace({'N':False,'Y':True})

## QUESTIONS TO SOLVE

## 1. HOW MANY MATHES ARE THERE IN TOTAL

In [ ]:
f'Total Macthes In Played In Ipl from 2008 to 2024 is {ipl.shape[0]}'

'Total Macthes In Played In Ipl from 2008 to 2024 is 1095'

## 2.HOW MANY SEASONS ARE PRESENT

In [ ]:
f'Total Seasons Ipl Hosted {ipl['season'].nunique()}'

'Total Seasons Ipl Hosted 17'

## 3.HOW MANY UNQIE TEAMS PLAYED IN IPL

In [ ]:
f'All unquie team played in ipl {pd.concat([ipl['team1'],ipl['team2']]).nunique()}'

'All unquie team played in ipl 14'

## 4.WHICH CITIES HOSTED THE MOST MATCHES

In [ ]:
f'Most Matches Hosted City is {ipl['city'].value_counts().idxmax()}'

'Most Matches Hosted City is Mumbai'

## 5.WHAT ARE THE DIFF MATCH TYPES

In [ ]:
f'Diffrent Matche Types {ipl['match_type'].unique()}'

"Diffrent Matche Types ['League' 'Semi Final' 'Final' '3rd Place Play-Off' 'Qualifier 1'\n 'Elimination Final' 'Qualifier 2' 'Eliminator']"

## 6.HOW MANY MATCHES ARE MISSING CITY VALUES

In [ ]:
f'In ipl dataset Mising Cities Values is {ipl['city'][ipl['city']=='Unknown'].size}'

'In ipl dataset Mising Cities Values is 51'

## 7.HOW MANY MATCHES WENT TO SUPER OVER

In [ ]:
f'{ipl['super_over'].sum()} Macthes Super Over Played in Ipl History'

'14 Macthes Super Over Played in Ipl History'

## Team **Analysis**

## 8.WHICH TEAM WIN THE MOST MACTHES

In [ ]:
f'Most wins in the ipl is {ipl['winner'].value_counts().idxmax()} they won {ipl['winner'].value_counts().max()} Matches'

'Most wins in the ipl is Mumbai Indians they won 144 Matches'

## WHICH TEAM PLAYED THE MOST MACTHES

In [ ]:
f'Team That Is Played Most Macthes is {pd.concat([ipl['team1'],ipl['team2']]).value_counts().idxmax()} They Played {pd.concat([ipl['team1'],ipl['team2']]).value_counts().max()} Macthes'

'Team That Is Played Most Macthes is Mumbai Indians They Played 261 Macthes'

## WHAT IS THE WIN PERCENTAGE OF EACH TEAMS

In [ ]:
teams_played=pd.concat([ipl['team1'],ipl['team2']]).value_counts()
teams_wins=ipl['winner'].value_counts()

win_ratio={}
for team in pd.concat([ipl['team1'],ipl['team2']]).unique():
  win_ratio[team]= teams_wins[team]/teams_played[team]*100

In [ ]:
for key , value in win_ratio.items():
  print(f'{key} Team Win Ratio Is {value}',end='\n')

Royal Challengers Bengaluru Team Win Ratio Is 48.23529411764706
Punjab Kings Team Win Ratio Is 45.52845528455284
Delhi Capitals Team Win Ratio Is 45.63492063492063
Mumbai Indians Team Win Ratio Is 55.172413793103445
Kolkata Knight Riders Team Win Ratio Is 52.191235059760956
Rajasthan Royals Team Win Ratio Is 50.678733031674206
Sunrisers Hyderabad Team Win Ratio Is 45.525291828793776
Chennai Super Kings Team Win Ratio Is 57.98319327731093
Kochi Tuskers Kerala Team Win Ratio Is 42.857142857142854
Rising Pune Supergiants Team Win Ratio Is 26.08695652173913
Gujarat Lions Team Win Ratio Is 43.333333333333336
Rising Pune Supergiant Team Win Ratio Is 50.0
Lucknow Super Giants Team Win Ratio Is 54.54545454545454
Gujarat Titans Team Win Ratio Is 62.22222222222222

## WHICH TEAM AS THE HIGHEST WIN PERCENTAGE(min 50 matches)

In [ ]:
f'Which Team Won Most (Min:50 Match) {teams_played[teams_played>50].idxmax()}'

'Which Team Won Most (Min:50 Match) Mumbai Indians'

## WHICH TEAM WON THE MOST MATCHES IN SINGLE SEASON

In [ ]:
f'Most win single season {(ipl.groupby(['season','winner']).size().idxmax())}'

"Most win single season (np.int64(2008), 'Rajasthan Royals')"

In [ ]:
grp = ipl.groupby(['season','winner']).size()

f'Most win single season {grp.idxmax()} with {grp.max()} wins'

"Most win single season (np.int64(2008), 'Rajasthan Royals') with 13 wins"

## most wins when team is chose to bat

In [ ]:
ipl_batdecision=ipl[ipl['toss_decision']=='bat']
ipl_batdecision.groupby('winner').size().idxmax()

'Chennai Super Kings'

In [ ]:
ipl[ipl['toss_decision'] == 'bat']['winner'].value_counts().idxmax()

'Chennai Super Kings'

## WHICH TEAM WINS MORE WHEN BATTING FIRST VS CHASING

In [ ]:
ipl_batdecision=ipl[ipl['toss_decision']=='bat']
f'Most Win Batting First is {ipl_batdecision.groupby('winner').size().idxmax() }'

'Most Win Batting First is Chennai Super Kings'

In [ ]:
ipl_bowldecision=ipl[ipl['toss_decision']=='field']
f'Most Wins When Chasing is {ipl_bowldecision.groupby('winner').size().idxmax()}'

'Most Wins When Chasing is Mumbai Indians'

In [ ]:
better=pd.concat((ipl_batdecision['winner'].value_counts(),ipl_bowldecision['winner'].value_counts()),axis=1)
better.columns=['Bat_First_Wins',"Chasing_wins"]

In [ ]:
better['statargy']=np.where(better['Bat_First_Wins']>better['Chasing_wins'],'Bat','Chase')

In [ ]:
better

                             Bat_First_Wins  Chasing_wins statargy
winner
Chennai Super Kings                    63.0            75    Chase
Mumbai Indians                         54.0            90    Chase
Kolkata Knight Riders                  50.0            81    Chase
Sunrisers Hyderabad                    44.0            73    Chase
Rajasthan Royals                       43.0            69    Chase
Delhi Capitals                         42.0            73    Chase
Royal Challengers Bengaluru            38.0            85    Chase
Punjab Kings                           28.0            84    Chase
Rising Pune Supergiants                 9.0             3      Bat
Gujarat Titans                          9.0            19    Chase
Lucknow Super Giants                    6.0            18    Chase
Gujarat Lions                           2.0            11    Chase
Rising Pune Supergiant                  2.0            13    Chase
No Result                               1.0             4    Chase
Kochi Tuskers Kerala                    NaN             6    Chase

In [ ]:
# 🏏 Batting First Wins (won by runs)
bat_first = ipl[ipl["result"] == "runs"]

# 🎯 Chasing Wins (won by wickets)
chase = ipl[ipl["result"] == "wickets"]

# -----------------------------
# 📊 Team-wise analysis
# -----------------------------
print("🏏 Batting First Wins (Team-wise):\n")
print(bat_first["winner"].value_counts())

print("\n🎯 Chasing Wins (Team-wise):\n")
print(chase["winner"].value_counts())

# -----------------------------
# 📌 TOTAL COMPARISON
# -----------------------------
print("\n📊 TOTAL WIN COMPARISON:")
print("Batting First Wins:", bat_first.shape[0])
print("Chasing Wins:", chase.shape[0])

🏏 Batting First Wins (Team-wise):

winner
Chennai Super Kings            71
Mumbai Indians                 71
Sunrisers Hyderabad            62
Royal Challengers Bengaluru    57
Kolkata Knight Riders          54
Punjab Kings                   51
Delhi Capitals                 46
Rajasthan Royals               43
Lucknow Super Giants           16
Gujarat Titans                 11
Rising Pune Supergiant          7
Rising Pune Supergiants         6
Kochi Tuskers Kerala            2
Gujarat Lions                   1
Name: count, dtype: int64

🎯 Chasing Wins (Team-wise):

winner
Kolkata Knight Riders          76
Mumbai Indians                 71
Chennai Super Kings            67
Rajasthan Royals               67
Delhi Capitals                 66
Royal Challengers Bengaluru    64
Punjab Kings                   58
Sunrisers Hyderabad            54
Gujarat Titans                 17
Gujarat Lions                  12
Rising Pune Supergiant          8
Lucknow Super Giants            8
Rising Pune Supergiants         6
Kochi Tuskers Kerala            4
Name: count, dtype: int64

📊 TOTAL WIN COMPARISON:
Batting First Wins: 498
Chasing Wins: 578

## we can also write like this

In [ ]:
ipl_batdecision['winner'].value_counts().idxmax()

'Chennai Super Kings'

In [ ]:
ipl_bowldecision['winner'].value_counts().idxmax()

'Mumbai Indians'

## Level 2:

## How many times did the toss winner also win the match?

In [ ]:
f'{ipl[ipl['toss_winner']==ipl['winner']].groupby('winner').size().idxmax()} won the toss as well as match most times'

'Mumbai Indians won the toss as well as match most times'

In [ ]:
f'{ipl[ipl['toss_winner']==ipl['winner']].shape[0]} many times toss winner also win the match'

'554 many times toss winner also win the match'

## What is the toss win → match win percentage?

In [ ]:
f'toss winer also match win percentage is {round(ipl[ipl['toss_winner']==ipl['winner']].shape[0]/ipl.shape[0]*100,2)} % '

'toss winer also match win percentage is 50.59 % '

In [ ]:
f'{ipl[ipl['toss_winner']!=ipl['winner']].shape[0]} many times toss winner loss the match'

'541 many times toss winner loss the match'

## Which team benefits the most from winning the toss?

In [ ]:
f'Team that most win toss {ipl['toss_winner'].value_counts().idxmax()}'

'Team that most win toss Mumbai Indians'

## What is the most common toss decision (bat or field)?

In [ ]:
f'Most repeated decision after winning toss {ipl.groupby('toss_decision').size().idxmax()}'

'Most repeated decision after winning toss field'

In [ ]:
ipl['toss_decision'].value_counts().idxmax()

'field'

## Does choosing to bat first increase chances of winning?

In [ ]:
choose_bat=ipl[ipl['toss_decision']=='bat']
choose_bat[choose_bat['toss_winner']==choose_bat['winner']].shape[0]

177

In [ ]:
print(f'{choose_bat.shape[0]} teams choose to bat when toss win but {choose_bat[choose_bat['toss_winner']==choose_bat['winner']].shape[0]} mathes win')
print(f'{choose_bat[choose_bat['toss_winner']==choose_bat['winner']].shape[0]/choose_bat.shape[0]*100} % Winning Ratio')

391 teams choose to bat when toss win but 177 mathes win
45.26854219948849 % Winning Ratio

In [ ]:
choose_field=ipl[ipl['toss_decision']=='field']
chfield_win=choose_field[choose_field['toss_winner']==choose_field['winner']]

In [ ]:
print(f'{choose_field.shape[0]} teams choose to bat when toss win but {choose_field[choose_field['toss_winner']==choose_field['winner']].shape[0]} mathes win')
print(f'{choose_field[choose_field['toss_winner']==choose_field['winner']].shape[0]/choose_field.shape[0]*100} % Winning Ratio')

704 teams choose to bat when toss win but 377 mathes win
53.55113636363637 % Winning Ratio

In [ ]:
print(f'{choose_bat.shape[0]} teams choose to bat when toss win but {choose_bat[choose_bat['toss_winner']==choose_bat['winner']].shape[0]} mathes win')
print(f'{choose_bat[choose_bat['toss_winner']==choose_bat['winner']].shape[0]/choose_bat.shape[0]*100} % Winning Ratio')
print(f'{choose_field.shape[0]} teams choose to bat when toss win but {choose_field[choose_field['toss_winner']==choose_field['winner']].shape[0]} mathes win')
print(f'{choose_field[choose_field['toss_winner']==choose_field['winner']].shape[0]/choose_field.shape[0]*100} % Winning Ratio')
f'Final answer choose to bat winning ratio is less chance to win as compared to field first because they known the exact score to chase'

391 teams choose to bat when toss win but 177 mathes win
45.26854219948849 % Winning Ratio
704 teams choose to bat when toss win but 377 mathes win
53.55113636363637 % Winning Ratio

'Final answer choose to bat winning ratio is less chance to win as compared to field first because they known the exact score to chase'

## Level 4

Who has the most Player of the Match awards?

In [ ]:
f'Most Player of the match award goes to {ipl['player_of_match'].value_counts().idxmax()}'

'Most Player of the match award goes to AB de Villiers'

## Top 10 players with most awards

In [ ]:
print(f'Top 10 Player of the match winners')
print(ipl['player_of_match'].value_counts()[:10])

Top 10 Player of the match winners
player_of_match
AB de Villiers    25
CH Gayle          22
RG Sharma         19
DA Warner         18
V Kohli           18
MS Dhoni          17
RA Jadeja         16
YK Pathan         16
SR Watson         16
AD Russell        15
Name: count, dtype: int64

## Which player has most awards in a single season?

In [ ]:
grp = ipl.groupby('season')['player_of_match'].value_counts()

print(f"Most Award in single season {grp.idxmax()} with {grp.max()} awards")

Most Award in single season (np.int64(2011), 'CH Gayle') with 6 awards

## Which player performs best in finals (if match_type includes finals)?

In [ ]:
print('There is no single best performer in finals; multiple players have won Player of the Match once each')
print(ipl[ipl['match_type']=='Final']['player_of_match'].value_counts())

There is no single best performer in finals; multiple players have won Player of the Match once each
player_of_match
YK Pathan       1
A Kumble        1
SK Raina        1
M Vijay         1
MS Bisla        1
KA Pollard      1
MK Pandey       1
RG Sharma       1
BCJ Cutting     1
KH Pandya       1
SR Watson       1
JJ Bumrah       1
TA Boult        1
F du Plessis    1
HH Pandya       1
DP Conway       1
MA Starc        1
Name: count, dtype: int64

## Level 5: Venue & City Insights

Which venue hosted the most matches?

## First We are making Ground Name As same some of the cell contain duplicate names

In [ ]:
ipl['venue'].replace({

"M Chinnaswamy Stadium, Bengaluru": "M Chinnaswamy Stadium",
"M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",

"Wankhede Stadium": "Wankhede Stadium, Mumbai",

"MA Chidambaram Stadium, Chepauk, Chennai": "MA Chidambaram Stadium",
"MA Chidambaram Stadium Chepauk": "MA Chidambaram Stadium",
"MA Chidambaram Stadium, Chepauk": "MA Chidambaram Stadium",

"Feroz Shah Kotla": "Arun Jaitley Stadium",
"Arun Jaitley Stadium Delhi": "Arun Jaitley Stadium",
"Arun Jaitley Stadium, Delhi": "Arun Jaitley Stadium",

"Punjab Cricket Association Stadium, Mohali": "PCA IS Bindra Stadium",
"Punjab Cricket Association IS Bindra Stadium": "PCA IS Bindra Stadium",
"Punjab Cricket Association IS Bindra Stadium, Mohali": "PCA IS Bindra Stadium",
"Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh": "PCA IS Bindra Stadium",

"Rajiv Gandhi International Stadium, Uppal": "Rajiv Gandhi International Stadium",
"Rajiv Gandhi International Stadium, Uppal, Hyderabad": "Rajiv Gandhi International Stadium",

"Eden Gardens, Kolkata": "Eden Gardens",

"Dr DY Patil Sports Academy, Mumbai": "Dr DY Patil Sports Academy",

"Maharashtra Cricket Association Stadium": "MCA Stadium",
"Maharashtra Cricket Association Stadium, Pune": "MCA Stadium",

"Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "ACA-VDCA Stadium",
"Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam": "ACA-VDCA Stadium",

"Brabourne Stadium, Mumbai": "Brabourne Stadium",

"Himachal Pradesh Cricket Association Stadium, Dharamsala":
"Himachal Pradesh Cricket Association Stadium",

"Sawai Mansingh Stadium, Jaipur": "Sawai Mansingh Stadium",

},inplace=True)

/tmp/ipykernel_3311/817861918.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ipl['venue'].replace({

In [ ]:
f'{ipl['venue'].value_counts().idxmax()} Host The Most matches In Ipl History Total: {ipl['venue'].value_counts().max()} Matches'

'Wankhede Stadium, Mumbai Host The Most matches In Ipl History Total: 118 Matches'

Which team has the most wins at each venue?

In [ ]:
var=ipl.groupby('venue')['winner']
for ground in ipl['venue'].unique():
  Ground=var.get_group(ground).value_counts()
  print(ground,  "Most Wins",Ground.idxmax(),"No Of Wins ",Ground.max())

M Chinnaswamy Stadium Most Wins Royal Challengers Bengaluru No Of Wins  44
PCA IS Bindra Stadium Most Wins Punjab Kings No Of Wins  31
Arun Jaitley Stadium Most Wins Delhi Capitals No Of Wins  37
Wankhede Stadium, Mumbai Most Wins Mumbai Indians No Of Wins  52
Eden Gardens Most Wins Kolkata Knight Riders No Of Wins  52
Sawai Mansingh Stadium Most Wins Rajasthan Royals No Of Wins  37
Rajiv Gandhi International Stadium Most Wins Sunrisers Hyderabad No Of Wins  39
MA Chidambaram Stadium Most Wins Chennai Super Kings No Of Wins  50
Dr DY Patil Sports Academy Most Wins Mumbai Indians No Of Wins  6
Newlands Most Wins Sunrisers Hyderabad No Of Wins  2
St George's Park Most Wins Chennai Super Kings No Of Wins  2
Kingsmead Most Wins Delhi Capitals No Of Wins  3
SuperSport Park Most Wins Rajasthan Royals No Of Wins  2
Buffalo Park Most Wins Mumbai Indians No Of Wins  1
New Wanderers Stadium Most Wins Royal Challengers Bengaluru No Of Wins  3
De Beers Diamond Oval Most Wins Punjab Kings No Of Wins  1
OUTsurance Oval Most Wins Punjab Kings No Of Wins  1
Brabourne Stadium Most Wins Mumbai Indians No Of Wins  7
Sardar Patel Stadium, Motera Most Wins Rajasthan Royals No Of Wins  7
Barabati Stadium Most Wins Sunrisers Hyderabad No Of Wins  3
Vidarbha Cricket Association Stadium, Jamtha Most Wins Sunrisers Hyderabad No Of Wins  2
Himachal Pradesh Cricket Association Stadium Most Wins Punjab Kings No Of Wins  5
Nehru Stadium Most Wins Kochi Tuskers Kerala No Of Wins  2
Holkar Cricket Stadium Most Wins Punjab Kings No Of Wins  4
ACA-VDCA Stadium Most Wins Delhi Capitals No Of Wins  3
Subrata Roy Sahara Stadium Most Wins Rising Pune Supergiants No Of Wins  4
MCA Stadium Most Wins Chennai Super Kings No Of Wins  6
Shaheed Veer Narayan Singh International Stadium Most Wins Delhi Capitals No Of Wins  4
JSCA International Stadium Complex Most Wins Chennai Super Kings No Of Wins  3
Sheikh Zayed Stadium Most Wins Kolkata Knight Riders No Of Wins  6
Sharjah Cricket Stadium Most Wins Punjab Kings No Of Wins  5
Dubai International Cricket Stadium Most Wins Chennai Super Kings No Of Wins  9
Saurashtra Cricket Association Stadium Most Wins Gujarat Lions No Of Wins  3
Green Park Most Wins Gujarat Lions No Of Wins  2
Narendra Modi Stadium, Ahmedabad Most Wins Gujarat Titans No Of Wins  9
Zayed Cricket Stadium, Abu Dhabi Most Wins Kolkata Knight Riders No Of Wins  2
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow Most Wins Lucknow Super Giants No Of Wins  7
Barsapara Cricket Stadium, Guwahati Most Wins Punjab Kings No Of Wins  2
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur Most Wins Punjab Kings No Of Wins  1

In [ ]:
print(ipl.groupby('venue')['winner'].apply(lambda x: x.value_counts().idxmax()))

venue
ACA-VDCA Stadium                                                                      Delhi Capitals
Arun Jaitley Stadium                                                                  Delhi Capitals
Barabati Stadium                                                                 Sunrisers Hyderabad
Barsapara Cricket Stadium, Guwahati                                                     Punjab Kings
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow           Lucknow Super Giants
Brabourne Stadium                                                                     Mumbai Indians
Buffalo Park                                                                          Mumbai Indians
De Beers Diamond Oval                                                                   Punjab Kings
Dr DY Patil Sports Academy                                                            Mumbai Indians
Dubai International Cricket Stadium                                              Chennai Super Kings
Eden Gardens                                                                   Kolkata Knight Riders
Green Park                                                                             Gujarat Lions
Himachal Pradesh Cricket Association Stadium                                            Punjab Kings
Holkar Cricket Stadium                                                                  Punjab Kings
JSCA International Stadium Complex                                               Chennai Super Kings
Kingsmead                                                                             Delhi Capitals
M Chinnaswamy Stadium                                                    Royal Challengers Bengaluru
MA Chidambaram Stadium                                                           Chennai Super Kings
MCA Stadium                                                                      Chennai Super Kings
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur                      Punjab Kings
Narendra Modi Stadium, Ahmedabad                                                      Gujarat Titans
Nehru Stadium                                                                   Kochi Tuskers Kerala
New Wanderers Stadium                                                    Royal Challengers Bengaluru
Newlands                                                                         Sunrisers Hyderabad
OUTsurance Oval                                                                         Punjab Kings
PCA IS Bindra Stadium                                                                   Punjab Kings
Rajiv Gandhi International Stadium                                               Sunrisers Hyderabad
Sardar Patel Stadium, Motera                                                        Rajasthan Royals
Saurashtra Cricket Association Stadium                                                 Gujarat Lions
Sawai Mansingh Stadium                                                              Rajasthan Royals
Shaheed Veer Narayan Singh International Stadium                                      Delhi Capitals
Sharjah Cricket Stadium                                                                 Punjab Kings
Sheikh Zayed Stadium                                                           Kolkata Knight Riders
St George's Park                                                                 Chennai Super Kings
Subrata Roy Sahara Stadium                                                   Rising Pune Supergiants
SuperSport Park                                                                     Rajasthan Royals
Vidarbha Cricket Association Stadium, Jamtha                                     Sunrisers Hyderabad
Wankhede Stadium, Mumbai                                                              Mumbai Indians
Zayed Cricket Stadium, Abu Dhabi                                               Kolkata Knight Riders
Name: winner, dtype: object

## Which city has the highest average result margin?

In [ ]:
runwise_result_margin=ipl[(ipl['result']=='runs') & (~ipl['result'].isin(['tie','no result']))].groupby('city')['result_margin'].mean()

wicketwise_result_margin=ipl[(ipl['result']=='wickets') & (~ipl['result'].isin(['tie','no result']))].groupby('city')['result_margin'].mean()



print(f'{runwise_result_margin.idxmax()} Is Highest Result Margin Based On Runs {runwise_result_margin.max()}')

print(f'{wicketwise_result_margin.idxmax()} Is Highest Result Margin Based On wickets {wicketwise_result_margin.max()}')

Port Elizabeth Is Highest Result Margin Based On Runs 66.66666666666667
Cape Town Is Highest Result Margin Based On wickets 9.0

## Which venue favors chasing teams more?

## groupby(level=0).sum() = “merge same index values and add them”

In [ ]:
series=pd.concat((ipl[(ipl['toss_decision']=='field') & (ipl['toss_winner']==ipl['winner'])].groupby('venue').size(),ipl[(ipl['toss_decision']=='bat') & (ipl['toss_winner']!=ipl['winner'])].groupby('venue').size())).groupby(level=0).sum()

In [ ]:
series

venue
ACA-VDCA Stadium                                                          7
Arun Jaitley Stadium                                                     47
Barabati Stadium                                                          3
Barsapara Cricket Stadium, Guwahati                                       1
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow     6
Brabourne Stadium                                                        13
Buffalo Park                                                              1
De Beers Diamond Oval                                                     2
Dr DY Patil Sports Academy                                               20
Dubai International Cricket Stadium                                      23
Eden Gardens                                                             55
Green Park                                                                4
Himachal Pradesh Cricket Association Stadium                              5
Holkar Cricket Stadium                                                    8
JSCA International Stadium Complex                                        5
Kingsmead                                                                 7
M Chinnaswamy Stadium                                                    50
MA Chidambaram Stadium                                                   36
MCA Stadium                                                              17
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur        3
Narendra Modi Stadium, Ahmedabad                                         15
Nehru Stadium                                                             2
New Wanderers Stadium                                                     5
Newlands                                                                  2
OUTsurance Oval                                                           1
PCA IS Bindra Stadium                                                    34
Rajiv Gandhi International Stadium                                       43
Sardar Patel Stadium, Motera                                              6
Saurashtra Cricket Association Stadium                                    7
Sawai Mansingh Stadium                                                   37
Shaheed Veer Narayan Singh International Stadium                          4
Sharjah Cricket Stadium                                                  18
Sheikh Zayed Stadium                                                     16
St George's Park                                                          4
Subrata Roy Sahara Stadium                                                6
SuperSport Park                                                           8
Vidarbha Cricket Association Stadium, Jamtha                              1
Wankhede Stadium, Mumbai                                                 64
Zayed Cricket Stadium, Abu Dhabi                                          5
dtype: int64

In [ ]:
series.idxmax()

'Wankhede Stadium, Mumbai'

## Level 6: Season Trends
Is the number of matches increasing over seasons?

## How many matches were played each season?**bold text**

In [ ]:
print(f'Each Season Total Macthes')
print(ipl.groupby('season').size())

Each Season Total Macthes
season
2008    58
2009    57
2010    60
2011    73
2012    74
2013    76
2014    60
2015    59
2016    60
2017    59
2018    60
2019    60
2020    60
2021    60
2022    74
2023    74
2024    71
dtype: int64

## **Who** won the title each season?

In [ ]:
ipl[ipl['match_type']=='Final'].groupby('season').apply(lambda row:row['winner'].iloc[0])

/tmp/ipykernel_3311/780703849.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ipl[ipl['match_type']=='Final'].groupby('season').apply(lambda row:row['winner'].iloc[0])

season
2008         Rajasthan Royals
2009      Sunrisers Hyderabad
2010      Chennai Super Kings
2011      Chennai Super Kings
2012    Kolkata Knight Riders
2013           Mumbai Indians
2014    Kolkata Knight Riders
2015           Mumbai Indians
2016      Sunrisers Hyderabad
2017           Mumbai Indians
2018      Chennai Super Kings
2019           Mumbai Indians
2020           Mumbai Indians
2021      Chennai Super Kings
2022           Gujarat Titans
2023      Chennai Super Kings
2024    Kolkata Knight Riders
dtype: object

**## What is the largest victory margin and which team achieved it?**

In [ ]:
runwise_result_margin_highest=ipl[(ipl['result']=='runs') & (~ipl['result'].isin(['tie','no result']))].groupby('winner')['result_margin']

wicketwise_result_margin_highest=ipl[(ipl['result']=='wickets') & (~ipl['result'].isin(['tie','no result']))].groupby('winner')['result_margin']

In [ ]:
runwise_result_margin_highest.max().idxmax()

'Mumbai Indians'

In [ ]:
wicketwise_result_margin_highest.max().idxmax()

'Chennai Super Kings'

In [ ]:
runwise_result_margin_highest = ipl[ipl['result'] == 'runs'].groupby('winner')['result_margin'].max()

print(runwise_result_margin_highest.idxmax(), runwise_result_margin_highest.max())

Mumbai Indians 146.0

In [ ]:
wicketwise_result_margin_highest = ipl[ipl['result'] == 'wickets'].groupby('winner')['result_margin'].max()

print(wicketwise_result_margin_highest.idxmax(), wicketwise_result_margin_highest.max())

Chennai Super Kings 10.0

In [ ]:
margin_win=pd.concat((runwise_result_margin_highest,wicketwise_result_margin_highest),axis=1)
margin_win.columns=['Runs_Margin','Wicket_Margin']

In [ ]:
margin_win

                             Runs_Margin  Wicket_Margin
winner
Chennai Super Kings                 97.0           10.0
Delhi Capitals                      97.0           10.0
Gujarat Lions                        1.0            7.0
Gujarat Titans                      62.0            9.0
Kochi Tuskers Kerala                17.0            8.0
Kolkata Knight Riders              140.0           10.0
Lucknow Super Giants                75.0            8.0
Mumbai Indians                     146.0           10.0
Punjab Kings                       111.0           10.0
Rajasthan Royals                   105.0           10.0
Rising Pune Supergiant              61.0            9.0
Rising Pune Supergiants             38.0            7.0
Royal Challengers Bengaluru        144.0           10.0
Sunrisers Hyderabad                118.0           10.0

In [ ]:
datas=ipl[ipl['match_type']=='Final']
data=pd.concat((datas['player_of_match'],datas['winner'],(datas['city'])),axis=1)

In [ ]:
data.reset_index(drop=True)

   player_of_match                 winner          city
0        YK Pathan       Rajasthan Royals        Mumbai
1         A Kumble    Sunrisers Hyderabad  Johannesburg
2         SK Raina    Chennai Super Kings        Mumbai
3          M Vijay    Chennai Super Kings       Chennai
4         MS Bisla  Kolkata Knight Riders       Chennai
5       KA Pollard         Mumbai Indians       Kolkata
6        MK Pandey  Kolkata Knight Riders     Bengaluru
7        RG Sharma         Mumbai Indians       Kolkata
8      BCJ Cutting    Sunrisers Hyderabad     Bengaluru
9        KH Pandya         Mumbai Indians     Hyderabad
10       SR Watson    Chennai Super Kings        Mumbai
11       JJ Bumrah         Mumbai Indians     Hyderabad
12        TA Boult         Mumbai Indians       Unknown
13    F du Plessis    Chennai Super Kings         Dubai
14       HH Pandya         Gujarat Titans     Ahmedabad
15       DP Conway    Chennai Super Kings     Ahmedabad
16        MA Starc  Kolkata Knight Riders       Chennai

In [ ]:
data.set_index(['city','winner'])

                                   player_of_match
city         winner
Mumbai       Rajasthan Royals            YK Pathan
Johannesburg Sunrisers Hyderabad          A Kumble
Mumbai       Chennai Super Kings          SK Raina
Chennai      Chennai Super Kings           M Vijay
             Kolkata Knight Riders        MS Bisla
Kolkata      Mumbai Indians             KA Pollard
Bengaluru    Kolkata Knight Riders       MK Pandey
Kolkata      Mumbai Indians              RG Sharma
Bengaluru    Sunrisers Hyderabad       BCJ Cutting
Hyderabad    Mumbai Indians              KH Pandya
Mumbai       Chennai Super Kings         SR Watson
Hyderabad    Mumbai Indians              JJ Bumrah
Unknown      Mumbai Indians               TA Boult
Dubai        Chennai Super Kings      F du Plessis
Ahmedabad    Gujarat Titans              HH Pandya
             Chennai Super Kings         DP Conway
Chennai      Kolkata Knight Riders        MA Starc

In [ ]:
ipl.to_csv('ipl_cleaned1.csv')